version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --output-template-file outputsamtemplate.yml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputsamtemplate.yml