AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  mainLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./lf1
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::164646536897:role/service-role/mainLambda-role-683bcz5u'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET